version: "3.9"

services:
  # Service de la BDD Postgresql
  db:
    image: postgres # Image postgres disponible sur dockerHub
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pass # Mot de passe de la BDD
      POSTGRES_USER: user # Nom de l'utilisateur
      POSTGRES_DB: beer-db # Nom de la BDD
    ports:
      - "5432:5432" # Port PostgreSQL
    volumes:
      - data-beer:/var/lib/postgresql/data # Mapper le volume data-beer pour persister les données
      - ./sql:/docker-entrypoint-initdb.d/ # Mappe le dossier sql pour initialiser la base avec des scripts SQL au démarrage
    container_name: db_beer # Nom du container

  api:
    build:
      context: ./ # Indique où se trouve le Dockerfile de l'API
      dockerfile: dockerfile
    restart: always
    environment:
      DB_HOST: db # Nom ou IP du service de la BDD
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: beer-db
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    container_name: zytho_api

volumes:
  data-beer: # Déclaration du volume pour persister les données PostgreSQL
